blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"

urlpatterns = [
    path("", render_posts, name = "posts"),
    path("<int:post_id>", post_detail, name ="post_detail"),
    ]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name ='home'),
    path('blog/', include('blog.urls')),
    path('skill/', include('skill.urls'))
]

urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skill/urls.py
from django.urls import path
from .views import render_abilitys
app_name = "skill"
urlpatterns = [
    path('', render_abilitys, name='abilitys'),
]

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to ="blog/images/")
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length = 450)
    image = ImageField(upload_to ='portfolio/images/')
    url = URLField(blank=True)

skill/models.py
from django.db import models

class Ability(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to ='skill/images/')

blog/views.py
from django.shortcuts import render, get_object_or_404
from.models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts':posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render (request, 'post_detail.html', {"post": post} )

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()

    return render(request, 'home.html', {'projects': projects})

skill/views.py
from django.shortcuts import render
from .models import Ability


def render_abilitys(request):
    abilitys = Ability.objects.all()
    return render(request, 'ability.html', {'abilitys': abilitys })

blog/templates/post_detail.html
{% extends 'layout.html' %}
    {% block content %}
        <h1 style="color:#ffff">Post</h1>

        <h2 style="color:#ffff">{{post.title}}</h2>
        <h4 style="color:#ffff">{{post.date}}</h4>

        <p style="color:#ffff" >{{post.description|safe}}</p>
        <img src ="{{post.image.url}}" alt="{{post.title}}">
    {% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}
<h1 style= "color:#ffff">Posts</h1>
<div class="d-flex flex-wrap">
    {% for post in posts%}
    <div class="card col-md-3" style=" margin: 10px;">
        <img src="{{post.image.url}}" class="card-img-top" alt="{{post.title}}">
        <div class="card-body">
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">{{post.description|truncatechars:100}}</p>
            <p class="card-text">{{post.date |date:'M d Y'}}</p>
            <a href="{% url 'blog:post_detail' post.id  %}" target="_blank" >{{post.title}}</a>
        </div>
    </div>
    {% endfor%}
{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}
<img class= "img-fluid" src={% static 'logoPortada.png' %} width="500px"; style=   "margin-top:100px"; "margin-right:20px"; >
<img class= "img-fluid" src={% static 'Avatar.png' %} width="720px">



<h1 style="color:#ffff"; "margin-left:20px" >Mis Proyectos</h1>
    <div class="d-flex flex-wrap">
    {% for project in projects %}
    <div class="card col-md-3" style=" margin: 10px 10px 10px 10px;">
        <img src="{{project.image.url}}" class="card-img-top" alt="{{project.title}}">
        <div class="card-body">
            <h5 class="card-title">{{project.title}}</h5>
            <p class="card-text">{{project.description}}</p>
            {% if project.url %}
                <a href="{{project.url}}" class="btn btn-primary">Link GitHub </a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<script src="https://kit.fontawesome.com/7ba0bb394d.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Django Portfolio</title>
</head>
<body>

    {% include 'partials/navbar.html' %}

    {% block content %}
    {% endblock %}
    {% include 'partials/footer.html' %}
</body>
</html>

portfolio/templates/partials/footer.html
{% load static %}

<section class = "footer">
    <div class="row">

      </div>
      <div class="row">
        <div class="col-12 col-md-6">
            <img class="img-fluid" style="margin-top:20px;" src ="{% static 'logofooter.png' %}"; width="500px" alt="">
        </div>
        <div class="col-12 col-md-6 d-flex flex-column flex-md-row align-items-start justify-content-between">
          <a href="https://www.facebook.com/SolartenaDev" target="_blank"><i class="bi bi-facebook"></i></a>
          <a href="https://twitter.com/SolartenaDev" target="_blank"><i class="bi bi-twitter"></i></a>
          <a href="https://www.instagram.com/solartenadev/" target="_blank"><i class="bi bi-instagram"></i></a>
          <a href="https://github.com/DianaSolarte" target="_blank"><i class="bi bi-github"></i></a>
          <a href="https://www.linkedin.com/in/diana-marcela-solarte-moreno-691492141/" target="_blank"><i class="bi bi-linkedin"></i></a>
        </div>
      </div>
<h3 class = "copyright" style="color:#ffff; font-size: 15px; text-align: center;">Copyright 2023. Made by Diana Solarte (@SolartenaDEV)</h3>
</section>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
      <div class="navbar-logo">
      <a class="navbar-brand" href="{% url 'home' %}"> <img src ="{% static 'logot.png' %}" width="60px" alt=""></a>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav pull-xs-right">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'skill:abilitys' %}">My Skills</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="">Contact</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-light btn-sm "href= "{% static 'CurrículumDianaSolarte.pdf' %}" target="_blanck" >Descargar CV</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-12 col-md-6 d-flex flex-column flex-md-row align-items-start justify-content-between">
      <a href="https://www.facebook.com/SolartenaDev" target="_blank"><i class="bi bi-facebook"></i></a>
      <a href="https://twitter.com/SolartenaDev" target="_blank"><i class="bi bi-twitter"></i></a>
      <a href="https://www.instagram.com/solartenadev/" target="_blank"><i class="bi bi-instagram"></i></a>
      <a href="https://github.com/DianaSolarte" target="_blank"><i class="bi bi-github"></i></a>
      <a href="https://www.linkedin.com/in/diana-marcela-solarte-moreno-691492141/" target="_blank"><i class="bi bi-linkedin"></i></a>
    </div>
  </div>
  </nav>

skill/templates/ability.html
{% extends 'layout.html' %}
{% block content %}

<h1 style= "color:#ffff">Mis Skills</h1>


    <div class="d-flex flex-wrap">
    {% for ability in abilitys %}
    <div class="card col-md-3" style=" margin: 10px;">
        <img src="{{ability.image.url}}" class="card-img-top" alt="{{ability.title}}">
        <div class="card-body">
            <h5 class="card-title">{{ability.title}}</h5>
            <p class="card-text">{{ability.description}}</p>
        </div>
    </div>
    {% endfor %}
{% endblock %}